server:
  port: 9003

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: http://localhost:8848
      # 配置中心
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
        shared-configs[0]:
          data-id: youlai-common.yaml
          refresh: true